rm -v	vrpn_3DConnexion.C \
	vrpn_3DMicroscribe.C \
	vrpn_3Space.C \
	vrpn_5DT16.C \
	vrpn_ADBox.C \
	vrpn_Analog_5dt.C \
	vrpn_Analog_5dtUSB.C \
	vrpn_Analog_Radamec_SPI.C \
	vrpn_Analog_USDigital_A2.C \
	vrpn_Atmel.C \
	vrpn_Button_NI_DIO24.C \
	vrpn_CerealBox.C \
	vrpn_Dyna.C \
	vrpn_DreamCheeky.C \
	vrpn_Event_Analog.C \
	vrpn_Event.C \
	vrpn_Event_Mouse.C \
	vrpn_Flock.C \
	vrpn_Flock_Parallel.C \
	vrpn_ForceDeviceServer.C \
	vrpn_Freespace.C \
	vrpn_FunctionGenerator.C \
	vrpn_GlobalHapticsOrb.C \
	vrpn_HumanInterface.C \
	vrpn_Imager_Stream_Buffer.C \
	vrpn_ImmersionBox.C \
	vrpn_inertiamouse.C \
	vrpn_JoyFly.C \
	vrpn_Joylin.C \
	vrpn_Keyboard.C \
	vrpn_Local_HIDAPI.C \
	vrpn_LUDL.C \
	vrpn_Magellan.C \
	vrpn_Mouse.C \
	vrpn_NationalInstruments.C \
	vrpn_nikon_controls.C \
	vrpn_Poser_Analog.C \
	vrpn_Poser_Tek4662.C \
	vrpn_raw_sgibox.C \
	vrpn_sgibox.C \
	vrpn_Spaceball.C \
	vrpn_Tng3.C \
	vrpn_Tracker_3DMouse.C \
	vrpn_Tracker_AnalogFly.C \
	vrpn_Tracker_ButtonFly.C \
	vrpn_Tracker_Crossbow.C \
	vrpn_Tracker_DTrack.C \
	vrpn_Tracker_Fastrak.C \
	vrpn_Tracker_GameTrak.C \
	vrpn_Tracker_isense.C \
	vrpn_Tracker_Isotrak.C \
	vrpn_Tracker_Liberty.C \
	vrpn_Tracker_MotionNode.C \
	vrpn_Tracker_NDI_Polaris.C \
	vrpn_Tracker_PhaseSpace.C \
	vrpn_Tracker_TrivisioColibri.C \
	vrpn_Tracker_NovintFalcon.C \
	vrpn_Tracker_SpacePoint.C \
	vrpn_Tracker_WiimoteHead.C \
	vrpn_UNC_Joystick.C \
	vrpn_VPJoystick.C \
	vrpn_Wanda.C \
	vrpn_WiiMote.C \
	vrpn_Xkeys.C \
	vrpn_Zaber.C \
	vrpn_3DConnexion.h \
	vrpn_3DMicroscribe.h \
	vrpn_3Space.h \
	vrpn_5DT16.h \
	vrpn_ADBox.h \
	vrpn_Analog_5dt.h \
	vrpn_Analog_5dtUSB.h \
	vrpn_Analog_Radamec_SPI.h \
	vrpn_Analog_USDigital_A2.h \
	vrpn_Atmel.h \
	vrpn_Button_NI_DIO24.h \
	vrpn_CerealBox.h \
	vrpn_Dyna.h \
	vrpn_DreamCheeky.h \
	vrpn_Event_Analog.h \
	vrpn_Event.h \
	vrpn_Event_Mouse.h \
	vrpn_Flock.h \
	vrpn_Flock_Parallel.h \
	vrpn_ForceDeviceServer.h \
	vrpn_Freespace.h \
	vrpn_GlobalHapticsOrb.h \
	vrpn_HumanInterface.h \
	vrpn_Imager_Stream_Buffer.h \
	vrpn_ImmersionBox.h \
	vrpn_inertiamouse.h \
	vrpn_JoyFly.h \
	vrpn_Joylin.h \
	vrpn_Keyboard.h \
	vrpn_LUDL.h \
	vrpn_Magellan.h \
	vrpn_Mouse.h \
	vrpn_NationalInstruments.h \
	vrpn_nikon_controls.h \
	vrpn_Poser_Analog.h \
	vrpn_Poser_Tek4662.h \
	vrpn_raw_sgibox.h \
	vrpn_sgibox.h \
	vrpn_Spaceball.h \
	vrpn_Tng3.h \
	vrpn_Tracker_3DMouse.h \
	vrpn_Tracker_AnalogFly.h \
	vrpn_Tracker_ButtonFly.h \
	vrpn_Tracker_Crossbow.h \
	vrpn_Tracker_DTrack.h \
	vrpn_Tracker_Fastrak.h \
	vrpn_Tracker_GameTrak.h \
	vrpn_Tracker_isense.h \
	vrpn_Tracker_Isotrak.h \
	vrpn_Tracker_Liberty.h \
	vrpn_Tracker_MotionNode.h \
	vrpn_Tracker_NDI_Polaris.h \
	vrpn_Tracker_PhaseSpace.h \
	vrpn_Tracker_SpacePoint.h \
	vrpn_Tracker_TrivisioColibri.h \
	vrpn_Tracker_NovintFalcon.h \
	vrpn_Tracker_WiimoteHead.h \
	vrpn_UNC_Joystick.h \
	vrpn_VPJoystick.h \
	vrpn_Wanda.h \
	vrpn_WiiMote.h \
	vrpn_Xkeys.h \
	vrpn_Zaber.h

